# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
import os

# CONFIG = 'config/config.yml'
# configfile: CONFIG

rule all:
    input:
        'results/irrigation_policy_maps'
        # 'results/fig/fig1.png',
        # 'results/fig/fig2.png',
        # 'results/fig/fig3.png',
        # 'results/fig/fig4.png'

# rule prepare_command_areas:
#     input:
#         script='workflow/scripts/prepare-command-areas.R'

rule make_irrig_policy:
    input:
        script='workflow/scripts/make-irrig-policy.R'
    output:
        directory('results/irrigation_policy_maps')
    params:
        None
    resources:
        time = '00:30:00',
        mem_mb = 4000,
        partition = 'short'
    shell:
        """
        Rscript {input.script} {output}
        """

# TODO this will have to be done on a server (JULES output too large)
# rule process_jules_output:
#     input:
#         script='workflow/scripts/process-jules-output.py'
#     output:
#         directory()
#     params:
#         None
#     resources:
#         time = '00:30:00',
#         mem_mb = 4000,
#         partition = 'short'
#     shell:
#         """
#         Rscript {input.script} {output}
#         """

# rule compute_water_balance:
#     input:
#         script='workflow/scripts/compute-water-balance.R'

# rule select_gleam_data:
#     input:
#         script='workflow/scripts/select-gleam-data.sh'

# rule validate_jules_output:
#     input:
#         script='workflow/scripts/validate-jules-output.R'

# rule make_plots:
#     input:
#         script='workflow/scripts/make-plots.R'
