name: conda_environment_base
channels:
  - conda-forge
  - defaults
dependencies:
  - bottleneck
  - cdo
  - click
  - dask
  - geopandas
  - iris
  - netCDF4
  - pandas
  - pyflwdir
  - python=3
  - pip
  - pyarrow
  - rasterio
  - shapely
  - tqdm
  - xarray
